name = "microsite-hits"
main = "src/index.js"
compatibility_date = "2026-06-01"
account_id = "89faf73996d0845a99ce853341011924"

[[kv_namespaces]]
binding = "HITS"
id = "6bf9f19059f2461d8a50824a9af3790a"

[observability]
enabled = true
